/*
 * @Author: tao.w
 * @Date: 2019-08-29 17:46:43
 * @LastEditors: tao.w
 * @LastEditTime: 2021-04-29 21:22:11
 * @Description: 
 */
/**
 * map editor CSS and JS library
 */
;;(function() {
    // var root = window.KDSEditorLibraryPath= "http://192.168.5.34:40020/web_editor/editor/app/road-editor/";
    var host = location.host; 
//  var root = "http://"+host+"/web_editor/editor/app/road-editor/";
//  window.KDSEditorLibraryPath="http://"+host+"/web_editor/editor/";
    var pathname = window.location.pathname;
    var protocol = window.location.protocol;
    if(pathname.indexOf('/') != 0){
    	pathname = '/' + pathname;
    }
    var endstr = '/editor/app/road-editor/';
    var root = protocol + '//' + host + pathname;
    root = root.split(endstr)[0] + endstr;
    window.KDSEditorLibraryPath = root.replace('/editor/app/road-editor/', '/editor/');
    //var root = window.KDSEditorLibraryPath= "http://10.61.48.81:8080/MapEditor-API/";
    //var root = window.KDSEditorLibraryPath= "http://localhost:8080//road/";
    // var root = "http://192.168.5.34:40020/web_editor/editor/app/road-editor/";
    // var root = "";
    if(location.hostname == "localhost"){
        root = "";
        window.KDSEditorLibraryPath="http://"+host+"/editor/"
    }
    var css = "../../css",
        script = "../../js",
        dataDir = "../../data",
        config = dataDir + "/config";

    //当前app目录
    var appDir = '.';

    // CSS
    var cssStore = [
        css + '/reset.css',
        script + '/lib/video/video-js-7.11.2.min.css',
        css + '/map.css',
        css + '/app.css',
        css + '/potree.css',
        css + '/bs3-table.css',
        css + '/feature-icons.css',
        css + '/walk.css',
        css + '/iconfont.css',
        appDir + '/css/road.css',
        appDir + '/css/leftbar.css',
        appDir + '/css/reportform.css',
        appDir + '/css/toporefresh.css',
        appDir + '/css/effectform.css',
        appDir + '/css/widget.css',
        appDir + '/css/edit_tip.css',
        appDir + '/css/autocheck.css',
        appDir + '/css/effects.css',
        appDir + '/css/line_info.css',
        appDir + '/css/potree_player.css',
        appDir + '/css/dvr.css',
        appDir + '/css/road_filter.css',
        appDir + '/css/node_search.css',
        appDir + '/css/editcheck_tag_panel.css',
        appDir + '/css/dialog.css',
        appDir + '/css/opendialog.css',
        appDir + '/css/tag_editor.css',
        appDir + '/css/select2.min.css'
        
        ]

    // SCRIPT
    var scriptStore = [
        // script + '/lib/jquery.min.js',
        script + '/lib/jquery/jquery-3.1.1.min.js',
//      script + '/lib/e-smart-zoom-jquery.js',
        script + '/lib/jquery.cookie.js',
        script + '/lib/jquery.oauth2-client.js',
        script + '/lib/lodash.js',
        script + '/lib/echarts.min.js',
        script + '/lib/d3.v3.js',
        script + '/lib/turf.js',
//      script + '/lib/sylvester.src.js',
        script + '/lib/matrix.js',
        // script + '/lib/opencv.js',
        script + '/lib/ML_MATRIX.js',
        
        script + '/lib/UTM.js',
        script + '/lib/osmauth.js',
        script + '/lib/jxon.js',
        script + '/lib/wkx.js',
        script + '/lib/d3.typeahead.js',
        script + '/lib/d3.combobox.js',
        script + '/lib/d3.geo.tile.js',
        script + '/lib/d3.dimensions.js',
        script + '/lib/clipper.js',
        script + '/lib/d3.trigger.js',
        script + '/lib/d3.jsonp.js',
        script + '/lib/d3.widget.js',
        script + '/lib/d3.widget.helper.js',
        script + '/lib/d3.keybinding.js',
        script + '/lib/d3.curtain.js',
        script + '/lib/d3.one.js',
        script + '/lib/d3.value.js',
        script + '/lib/d3-compat.js',
        script + '/lib/bootstrap-tooltip.js',
        script + '/lib/bootstrap-pagination.js',
        script + '/lib/bootstrap-tabs.js',
        script + '/lib/rbush.js',
        script + '/lib/sexagesimal.js',
        script + '/lib/togeojson.js',
        script + '/lib/marked.js',
        script + '/lib/mustache.js',
        script + '/lib/colorPicker.js',
        script + '/lib/bootstrap-timepicker.js',
        script + '/lib/select2.min.js',
        // script + '/lib/jquery.dataTables.min.js',
        script + '/lib/clipboard.min.js',

        script + '/lib/three.js/build/three.min.js',
        script + '/lib/other/PLYLoader.js',
        script + '/lib/MeshLine/MeshLine.js',
        

        
        script + '/lib/spectrum/spectrum.js',
        script + '/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js',
        script + '/lib/jquery-ui/jquery-ui.min.js',
        script + '/lib/other/BinaryHeap.js',
        script + '/lib/tween/tween.min.js',
        // script + '/lib/d3/d3.js',
        script + '/lib/proj4/proj4.js',
        script + '/lib/plasio/js/laslaz.js',
        script + '/lib/openlayers3/ol.js',
        script + '/lib/i18next/i18next.js',
        script + '/lib/jstree/jstree.js',
        script + '/lib/potree/potree.js',
        script + '/lib/video/video-7.11.2.min.js',
        // script + '/lib/plasio/js/laslaz.js' ,
        
        script + '/lib/protobuf.min.js',
        script + '/lib/bvh.js',
		
		script + '/lib/jrange/jquery.range.js',

        script + '/lib/require.js',
        script + '/lib/zrender-original.js',
        script + '/id/id.js',
        
        
        appDir + '/track_control_point_handle.js',
        appDir + '/util.js',
        appDir + '/coordinates_util.js',
        appDir + '/config.js',
        //script + '/id/util.js',
        script + '/id/util/session_mutex.js',
        script + '/id/util/lass_extend.js',
        script + '/id/util/mapsheet.js',
        script + '/id/util/line_calculate.js',
        script + '/id/util/line_offset.js',
        script + '/id/util/tag_extend.js',
        script + '/id/util/roadcross_extend.js',
        script + '/id/util/data_validate.js',
        script + '/id/util/slop_extend.js',
        script + '/id/util/walk_extend.js',
        // script + '/id/util/xhr_multithreading.js',


        config + '/imagery.js',
        config + '/operations-sprite.js',
        config + '/specificationMap.js',
        config + '/locales.js',
        config + '/constant.js',
        config + '/template.js',
        config + '/dataLayers.js',
        config + '/id-store.js',

        dataDir + '/presets/categories.js',
        dataDir + '/presets/defaults.js',
        dataDir + '/presets/fields.js',
        dataDir + '/presets/presets.js',
        dataDir + '/locales/en.js',
        dataDir + '/locales/zh_cn.js',


        script + "/id/geo.js",
        script + "/id/geo/extent.js",
        script + "/id/geo/intersection.js",
        script + "/id/geo/maat.js",
        script + "/id/geo/multipolygon.js",
        script + "/id/geo/raw_mercator.js",

        script + '/id/renderer/background.js',
        script + '/id/renderer/background_source.js',
        script + '/id/renderer/gpx_layer.js',
        script + '/id/renderer/tile_layer.js',
        script + '/id/renderer/map.js',
        script + '/id/renderer/overview.js',
        script + '/id/renderer/overview_background.js',

        script + "/id/svg.js",
        script + "/id/svg/areas.js",
        script + "/id/svg/defs.js",
        script + "/id/svg/labels.js",
        script + "/id/svg/lines.js",
        script + "/id/svg/divider.js",
        script + "/id/svg/midpoints.js",
        script + "/id/svg/points.js",
        script + "/id/svg/surface.js",
        script + "/id/svg/tag_classes.js",
        script + "/id/svg/turns.js",
        script + "/id/svg/maat.js",
        script + "/id/svg/vertices.js",
        script + "/id/svg/transaction_areas.js",
        script + "/id/svg/walk_link.js",
        script + "/id/svg/walk_enter.js",
        script + "/id/svg/walk_areas.js",
        appDir + "/svg/traffic.js",
        appDir + "/svg/turn_guidance.js",
        appDir + "/svg/turn_guidance_seq.js",
        appDir + "/svg/pic_player_util.js",
        appDir + "/svg/auto_match.js",
        // appDir + "/svg/orthographic_map_auto_match.js",
        appDir + "/svg/potree_conversion.js",
        appDir + "/svg/pic_tool_epiline.js",
        appDir + "/svg/pic_draw_tool.js",
        appDir + "/svg/pic_tool_intersection.js",

        appDir + "/svg/potree_handle/object_pg.js",
        appDir + "/svg/potree_handle/trafficsign.js",
        appDir + "/svg/potree_handle/trafficlight.js",
        appDir + "/svg/potree_handle/bridge_facade.js",

		appDir + "/svg_pic/pic_draw.js",
		appDir + "/svg_pic/add_check_tag.js",
		appDir + "/svg_pic/add_image_tag.js",
		appDir + "/svg_pic/add_pick_mark_tag.js",
//		appDir + "/svg_pic/add_analysis_tag.js",
		appDir + "/svg_pic/add_question_tag.js",
		appDir + "/svg_pic/add_network_tag.js",
		appDir + "/svg_pic/add_board_polygon.js",
		appDir + "/svg_pic/add_board_polygon_plane.js",
		appDir + "/svg_pic/add_bridge_line.js",
		appDir + "/svg_pic/add_control_point.js",
		appDir + "/svg_pic/add_object_pt.js",
		appDir + "/svg_pic/add_outline_object_pt.js",
		appDir + "/svg_pic/add_divider_polygon.js",
		appDir + "/svg_pic/add_divider.js",
		appDir + "/svg_pic/add_ground_area.js",
		appDir + "/svg_pic/add_pavement_distress.js",
		appDir + "/svg_pic/add_pavement_distress_line.js",
		appDir + "/svg_pic/add_pavement_distress_line2.js",
		appDir + "/svg_pic/add_lamppost_lamp.js",
		appDir + "/svg_pic/add_lamppost.js",
		appDir + "/svg_pic/add_object_pg.js",
		appDir + "/svg_pic/add_object_pl.js",
		appDir + "/svg_pic/add_barrier_geometry.js",
		appDir + "/svg_pic/add_side_walk.js",
		appDir + "/svg_pic/add_road_attribute.js",
		appDir + "/svg_pic/add_trafficlight.js",
		
		appDir + "/svg_pic/default_button_list.js",
		appDir + "/svg_pic/btn_intersection.js",
		appDir + "/svg_pic/btn_batch_break_dref.js",
		appDir + "/svg_pic/btn_polyline_addnode.js",
		appDir + "/svg_pic/btn_tool_epiline_cross.js",
		appDir + "/svg_pic/split_board_line.js",
		appDir + "/svg_pic/add_divider_middlepoint.js",
		appDir + "/svg_pic/track_control_point.js",
		
        appDir + "/svg/pic_player_posform.js",
        appDir + "/svg/pic_player_trackcurve.js",
        appDir + "/svg/pic_player_trackcurve_form.js",
        appDir + "/svg/pic_player_footer.js",
        appDir + "/svg/pic_player_intersection_list.js",
        appDir + "/svg/pic_player.js",
        // appDir + "/svg/orthographic_map_player.js",
        appDir + "/svg/pic_sub_player.js",
        appDir + "/svg/potree.js",
        appDir + "/svg/pic_canvas.js",
        // appDir + "/svg/orthographic_map_canvas.js",
        appDir + "/svg/pic_canvas_work.js",
        appDir + "/svg/pic_data_mgr.js",
        // appDir + "/svg/orthographic_map_mgr.js",
        appDir + "/svg/road_cross_line.js",
        
        script + "/id/svg/roadcross.js",
        script + "/id/svg/roadzlevel.js",
        script + "/id/svg/speedcamera.js",
        script + "/id/svg/overview_surface.js",
        script + "/id/svg/overview_points.js",
        script + "/id/svg/placename.js",
        script + "/id/svg/searchpoint.js",
        script + "/id/svg/effects.js",
        script + "/id/svg/detailslope.js",
        script + "/id/svg/walkzlevel.js",

        appDir + "/ui.js",
        appDir + "/ui/road_tip.js",
        appDir + "/ui/road_merge_tip.js",
        appDir + '/ui/selection_list.js',
        appDir + "/ui/road_expand_tip.js",
        appDir + "/ui/dividernode_expand_tip.js",
        appDir + "/ui/divider_kerb_expand_tip.js",
        appDir + "/ui/barrier_offset_tip.js",
        appDir + "/ui/batch_offset_tip.js",
        appDir + "/ui/road_expand_animation.js",
        appDir + "/ui/tip_util.js",
        appDir + "/ui/adas_password_tip.js",


        appDir + "/ui/road_rule_gdf.js",
        appDir + "/ui/road_rule_editor.js",
        appDir + "/ui/road_control.js",
        appDir + "/ui/lane_connectivity_editor.js",
        appDir + "/ui/iDialog.js",
        appDir + "/ui/dialog.js",
        appDir + "/ui/iDrag.js",
        appDir + "/ui/ReportForm.js",
        appDir + "/ui/topoRefresh.js",
        appDir + "/ui/effectForm.js",
        appDir + "/ui/accuracyForm.js",
        appDir + "/ui/signpost_tag_editor.js",

        appDir + "/js/jsep.js",
        appDir + "/ui/road_filter_exp_parser.js",
        appDir + "/ui/road_filter_control.js",
        appDir + "/ui/node_line_info.js",
        appDir + "/ui/node_data_mgr.js",
        appDir + "/ui/road_filter_panel.js",
        
        appDir + "/ui/node_search_control.js",
        appDir + "/ui/node_search_panel.js",
        appDir + '/ui/editcheck_tag_control.js',
        appDir + '/ui/editcheck_tag_panel.js',
        appDir + '/ui/track_legend.js',
        appDir + '/ui/taskinfo_polygon.js',
        appDir + '/ui/taskWhiteList.js',
        appDir + '/ui/orthographic_switch.js',
        appDir + '/ui/use_ply.js',
        appDir + '/ui/use_height.js',
        appDir + '/ui/add_auto_checkwork_tag.js',
        appDir + '/ui/add_auto_network_tag.js',
        appDir + '/ui/distanceRLine.js',
        appDir + '/ui/deviceInfo.js',
        // appDir + '/ui/loadProtocol.js',
        appDir + '/ui/markupStatistics.js',

        appDir + '/topo/topo_handle.js',
        appDir + '/topo/topo_road_node.js',
        appDir + '/topo/topo_cross_maat.js',
        appDir + '/topo/topo_cross_maat_path.js',
        appDir + '/topo/topo_cross_rule.js',
        appDir + '/topo/topo_cross_saat.js',
        appDir + '/topo/topo_divider_attribute.js',
        appDir + '/topo/topo_divider_node.js',
        appDir + '/topo/topo_lane_attribute.js',
        appDir + '/topo/topo_r_divider_dref.js',
        appDir + '/topo/topo_node_maat.js',
        appDir + '/topo/topo_node_maat_path.js',
        appDir + '/topo/topo_node_rule.js',
        appDir + '/topo/topo_node_saat.js',
        appDir + '/topo/topo_road_cross.js',
        appDir + '/topo/topo_road_rule.js',
        appDir + '/topo/topo_entity.js',
        appDir + '/topo/topo_check.js',
        appDir + '/topo/topo_walk_road.js',
        appDir + '/topo/topo_walk_zlevel.js',
        appDir + '/topo/topo_lane_connectivity.js',


        appDir + '/js/walkLinkDirection.js',
        appDir + '/js/adas.js',
        appDir + '/js/user.js',
        appDir + '/js/userBehavior.js',
        appDir + '/js/logger.js',
        appDir + '/js/user_job_heartbeat.js',
        appDir + '/js/md5.js',
        appDir + '/js/buried_statistics.js',
        appDir + '/js/usernameCache.js',
        appDir + '/js/task.js',
        appDir + '/js/check.js',
        appDir + '/js/ws.js',
        appDir + "/js/layers.js",
        appDir + '/map_init.js',
        appDir + '/ui/leftbar/leftBar.js',
        appDir + '/ui/leftbar/leftBarControl.js',
        appDir + '/ui/leftbar/leftBarUserPane.js',
        appDir + '/ui/leftbar/usernameDropdown.js',
        appDir + '/ui/leftbar/loginPane.js',
        appDir + '/ui/leftbar/dropdown.js',
        appDir + '/ui/leftbar/navtab.js',
        appDir + '/ui/leftbar/tabs/LeftBarElementTask.js',
        appDir + '/ui/leftbar/tabs/LeftBarElementTaskDetail.js',
        appDir + '/ui/leftbar/tabs/LeftBarElementElement.js',
        appDir + '/ui/leftbar/tabs/dropDownMaker.js',
        appDir + '/ui/leftbar/tabs/LeftBarElementTaskAttr.js',

        script + '/id/ui/intro.js',
        script + '/id/ui/attribution.js',
        script + '/id/ui/radial_menu.js',
        script + '/id/ui/inspector.js',
        script + '/id/ui/modal.js',
        script + '/id/ui/cmd.js',
        script + '/id/ui/success.js',
        script + '/id/ui/loading.js',
        script + '/id/ui/background.js',
        script + '/id/ui/clone_tags.js',
        script + '/id/ui/dialog.js',
        script + '/id/ui/opendialog.js',
        script + '/id/ui/modes.js',
        script + '/id/ui/help.js',
        script + '/id/ui/zoom_level.js',
        script + '/id/ui/layermanager.js',
        script + '/id/ui/poi_search.js',
        script + '/id/ui/notice.js',
        script + '/id/ui/flash.js',
        script + '/id/ui/save.js',
        script + '/id/ui/scale.js',
        script + '/id/ui/geolocate.js',
        script + '/id/ui/spinner.js',
        // script + '/id/ui/restore.js',
        script + '/id/ui/lasso.js',
        script + '/id/ui/toggle.js',
        script + '/id/ui/undo_redo.js',
        script + '/id/ui/task_list.js',
        script + '/id/ui/road_crossing.js',
        script + '/id/ui/zoom.js',
        script + '/id/ui/view_mode_change.js',

        appDir + '/effects/walkFT.js',
        appDir + '/effects/dividerArea.js',
        // appDir + '/effects/dividerTL.js',
        appDir + '/effects/trafficlightTs.js',
        appDir + '/effects/dividerRL.js',
        appDir + '/effects/dividerRG.js',
        appDir + '/effects/dividerRD.js',
        appDir + '/effects/dividerRT.js',
        appDir + '/effects/roadRS.js',
        appDir + '/effects/dividerDT.js',
        appDir + '/effects/landLL.js',
        appDir + '/effects/landLT.js',
        appDir + '/effects/landRPL.js',
        appDir + '/effects/landRSL.js',
        appDir + '/effects/landRSL_N.js',
        appDir + '/effects/landRR.js',
        // appDir + '/effects/barrier_geometry.js',
        appDir + '/effects/dividerSideWalk.js',
        appDir + '/effects/dividerDrefMemberArea.js',
        appDir + '/effects/labelField.js',
        appDir + '/effects/additionalDivider.js',
        appDir + '/effects/deleteDivider.js',
        appDir + '/effects/wayDirection.js',
        appDir + '/effects/laneHighlight.js',
        appDir + '/effects/effects_junction.js',
        appDir + '/effects/dividerAttrHighlight.js',
        appDir + '/effects/breakNodeHighligh.js',
        appDir + '/effects/roadHighlight.js',
        appDir + '/effects/default.js',
        appDir + '/effects/shapePoint.js',
        appDir + '/effects/dottedSoild.js',
        appDir + '/effects/objectPGFirstPoint.js',
        appDir + '/effects/measureInfoHighlight.js',
        appDir + '/effects/flagNodeHighligh.js',
        appDir + '/effects/dividerTollgateHighight.js',
        appDir + '/ui/effects.js',



        appDir + '/ui/raw_tagmark_editor.js',
        // appDir + '/ui/signpost_tag_editor.js',
        appDir + '/ui/inspectorTagList.js',
        appDir + '/ui/inspectorTagFilter.js',
        appDir + '/ui/raw_tag_editor.js',
        appDir + '/ui/openDialog.js',
        appDir + '/ui/open_tagmark_dialog.js',
        appDir + '/ui/open_checktag_dialog.js',
        appDir + '/ui/model_name_plane.js',
        appDir + '/ui/open_tollgate_dialog.js',

        appDir + '/ui/tag_editor/tag_editor.js',
        appDir + '/ui/tag_editor/tpl/tag_name.js',
        appDir + '/ui/tag_editor/tpl/road.js',
        appDir + '/ui/tag_editor/tpl/roadnode.js',
        appDir + '/ui/tag_editor/tpl/roadcross.js',
        appDir + '/ui/tag_editor/tpl/poi.js',
        appDir + '/ui/tag_editor/tpl/divider_attribute.js',
        appDir + '/ui/tag_editor/tpl/pavement_distress.js',
        appDir + '/ui/tag_editor/tpl/lane_attribute.js',
        appDir + '/ui/tag_editor/tpl/road_attribute.js',

        appDir + '/ui/tag_editor/autoassign/road.js',
        appDir + '/ui/tag_editor/autoassign/autocheck.js',
        appDir + '/ui/tag_editor/input/input.js',
        appDir + '/ui/tag_editor/input/inputgroup.js',
        appDir + '/ui/tag_editor/input/relations.js',
        appDir + '/ui/tag_editor/input/traffic_semantic.js',
        appDir + '/ui/tag_editor/input/maat.js',
        appDir + '/ui/tag_editor/input/check.js',
        appDir + '/ui/tag_editor/input/checkgroup.js',
        appDir + '/ui/tag_editor/input/select.js',
        appDir + '/ui/tag_editor/input/mulselect.js',
        appDir + '/ui/tag_editor/input/selectgroup.js',
        appDir + '/ui/tag_editor/input/selectgroup2.js',
        appDir + '/ui/tag_editor/input/combo.js',
        appDir + '/ui/tag_editor/road_tag_editor.js',
        appDir + '/ui/tag_editor/roadnode_tag_editor.js',
        appDir + '/ui/tag_editor/roadcross_tag_editor.js',
        appDir + '/ui/tag_editor/dividernode_tag_editor.js',
        appDir + '/ui/tag_editor/poi_tag_editor.js',
        appDir + '/ui/tag_editor/dividerattribute_tag_editor.js',
        appDir + '/ui/tag_editor/pavement_distress_tag_editor.js',
        appDir + '/ui/tag_editor/laneattribute_tag_editor.js',
        appDir + '/ui/tag_editor/roadattribute_tag_editor.js',

        appDir + '/ui/road_rule/car_list.js',
        appDir + '/ui/road_rule/date.js',
        appDir + '/ui/road_rule/time.js',
        appDir + '/ui/road_rule/date_range.js',
        appDir + '/ui/road_rule/multi_check.js',
        appDir + '/ui/road_rule/radio.js',
        appDir + '/ui/road_rule/time_range.js',
        appDir + '/ui/road_rule/weekday.js',
        appDir + '/ui/road_rule/holiday.js',
        appDir + '/ui/road_rule/season.js',
        appDir + '/ui/road_rule/weather.js',
        appDir + '/ui/road_rule/select.js',
        appDir + '/ui/road_rule/rule_type.js',


        script + '/id/ui/feature_list.js',
        script + '/id/ui/layer_pane.js',
        script + '/id/ui/search_list.js',
        script + '/id/ui/style_setting_list.js',
        //script + '/id/ui/selection_list.js',
        script + '/id/ui/preset_list.js',
        script + '/id/ui/entity_editor.js',
        script + '/id/ui/disclosure.js',
        script + '/id/ui/sidebar.js',
        // script + '/id/ui/raw_relation_editor.js',
        script + '/id/ui/confirm.js',
        //script + '/id/ui/panorama.js',
        script + '/id/ui/infowindow.js',


        // add
        script + '/id/ui/lasso_zoom.js',
        script + '/id/ui/toolbar.js',
        script + '/id/ui/sublayer_list.js',
		script + '/id/ui/mesh_split.js',
		script + '/id/ui/mesh_boundry_tip.js',

        script + '/id/ui/intro/navigation.js',
        script + '/id/ui/intro/point.js',
        script + '/id/ui/intro/area.js',
        script + '/id/ui/intro/line.js',
        // script + '/id/ui/intro/start_editing.js',
		script + '/id/ui/clone_tags.js',

        script + '/id/actions.js',
        script + "/id/actions/add_midpoint.js",
        script + "/id/actions/add_member.js",
        script + '/id/actions/add_entity.js',
        script + '/id/actions/add_vertex.js',
        script + "/id/actions/split_road.js",
        script + "/id/actions/split_divider.js",
        script + "/id/actions/split_dividing_line.js",
        script + '/id/actions/change_tags.js',
        script + '/id/actions/circularize.js',
        //script + '/id/actions/connect.js',
        appDir + '/action/connect.js',




        script + '/id/actions/delete_member.js',
        script + '/id/actions/delete_multiple.js',
        //script + '/id/actions/delete_node.js',
        //script + "/id/actions/delete_relation.js",
        //script + "/id/actions/delete_way.js",

        appDir + '/action/way_add_nodes.js',
        appDir + '/action/delete_node.js',
        appDir + "/action/delete_relation.js",
        appDir + "/action/delete_way.js",
        appDir + '/action/road_cross_add.js',
        appDir + '/action/road_cross_modify.js',
        appDir + '/action/create_island.js',

        appDir + "/action/add_maat.js",
        appDir + "/action/update_node.js",
        appDir + "/action/update_pavement_distress.js",
        appDir + "/action/update_realnode.js",
        appDir + "/action/process_inherit.js",
        appDir + "/action/process_mesh.js",
        appDir + "/action/create_walkRoad.js",
        appDir + "/action/create_lane_info.js",
        appDir + "/action/pavement_distrees_measureinfo.js",
        appDir + "/action/create_turn_guidance.js",
        appDir + "/action/rectifyDeviationFeature.js",
        appDir + "/action/add_auto_checkwork_tag.js",
        appDir + "/action/add_auto_network_tag.js",
        appDir + "/action/create_dividernode_measureinfo.js",
        appDir + "/action/create_virtual_measureinfo.js",
        appDir + "/action/boardToEllipse.js",

        script + '/id/actions/clone_multiple.js',
        script + '/id/actions/clone_way.js',
        script + '/id/actions/clone_roadway.js',
        script + '/id/actions/discard_tags.js',
        script + '/id/actions/disconnect.js',
        script + '/id/actions/join.js',
        //script + '/id/actions/merge.js',
        appDir + '/action/merge.js',
        appDir + '/action/create.js',
        script + '/id/actions/wayjoin.js',
        script + '/id/actions/waymerge.js',
        script + '/id/actions/merge_polygon.js',
        script + '/id/actions/move_node.js',
        script + '/id/actions/move.js',
        script + '/id/actions/move_line_split_tufu.js',
        script + '/id/actions/noop.js',
        script + '/id/actions/orthogonalize.js',
        script + '/id/actions/rotate_way.js',
        script + '/id/actions/restrict_turn.js',
        script + '/id/actions/reverse.js',
        script + '/id/actions/straighten.js',
        script + '/id/actions/bezier_spline.js',
        script + '/id/actions/split.js',
        script + '/id/actions/dividerDREF.js',
        script + '/id/actions/expand_barrier_geometryNode.js',
        script + '/id/actions/createdividerOPL.js',
        script + '/id/actions/delete_dividerOPL.js',
        // script + '/id/actions/createdividerOPG.js',
        // script + '/id/actions/delete_dividerOPG.js',
        script + '/id/actions/createdividerVirtualLane.js',
        script + '/id/actions/createdividerVirtualLaneCircle.js',
        script + '/id/actions/junction.js',
        script + '/id/actions/cancel_relations.js',
        script + '/id/actions/delete_divider_junction.js',
        script + '/id/actions/road_divider.js',
        script + '/id/actions/update_divider_node.js',
        script + '/id/actions/unrestrict_turn.js',
        script + '/id/actions/edit_relation.js',
        script + '/id/actions/change_node_members.js',
        script + '/id/actions/road_intersect.js',
        script + '/id/actions/expand_road.js',
        script + '/id/actions/expand_dividerNode.js',
        script + '/id/actions/horizontal_move.js',
        script + '/id/actions/topo_split.js',
        script + '/id/actions/connect_divider.js',
        script + '/id/behavior.js',
        script + '/id/behavior/add_way.js',
        script + '/id/behavior/drag.js',
        script + '/id/behavior/draw.js',
        script + '/id/behavior/draw_way.js',
        script + '/id/behavior/draw_land_cover_area.js',
        script + '/id/behavior/draw_board_area.js',
        script + '/id/behavior/draw_fusion_divider.js',
        script + '/id/behavior/draw_divider.js',
        script + '/id/behavior/draw_object_pl.js',
        script + '/id/behavior/draw_rectPG.js',
        script + '/id/behavior/draw_object_pg.js',
        script + '/id/behavior/draw_cut_divider.js',
        script + '/id/behavior/edit.js',
        script + '/id/behavior/hover.js',
        script + '/id/behavior/lasso.js',
        script + '/id/behavior/select.js',
        script + '/id/behavior/tail.js',
        script + '/id/behavior/draw_island.js',
        script + '/id/behavior/draw_placename.js',
        script + '/id/behavior/draw_road_attribute.js',

        //add
        script + '/id/behavior/lasso_zoom.js',

        appDir + '/behavior/road_cross_modify.js',
        appDir + '/behavior/lane_info_path_edit.js',
        appDir + '/behavior/editor_way.js',
        appDir + '/behavior/draw_barrier.js',
        appDir + '/behavior/draw_pavement_distress.js',
        appDir + '/behavior/draw_pavement_distress1.js',

        script + '/id/modes.js',
        script + '/id/modes/add_area.js',
        script + '/id/modes/add_board_area.js',
        script + '/id/modes/add_land_cover_area.js',
        script + '/id/modes/add_point.js',
        script + '/id/modes/add_point_checktag.js',
        script + '/id/modes/add_poi.js',
        script + '/id/modes/add_text_mark.js',
        script + '/id/modes/add_line.js',
        script + '/id/modes/add_object_pl.js',
        script + '/id/modes/add_rectPG.js',
        script + '/id/modes/add_object_pg.js',
        script + '/id/modes/add_fusion_divider.js',
        script + '/id/modes/add_road.js',
        script + '/id/modes/add_divider.js',
        script + '/id/modes/add_cut_divider.js',
        script + '/id/modes/browse.js',
        script + '/id/modes/drag_node.js',
        script + '/id/modes/draw_area.js',
        script + '/id/modes/draw_land_cover_area.js',
        script + '/id/modes/draw_board_area.js',
        script + '/id/modes/draw_line.js',
        script + '/id/modes/draw_object_pl.js',
        script + '/id/modes/draw_rectPG.js',
        script + '/id/modes/draw_object_pg.js',
        script + '/id/modes/draw_fusion_divider.js',
        script + '/id/modes/draw_divider.js',
        script + '/id/modes/draw_cut_divider.js',
        script + '/id/modes/move.js',
        script + '/id/modes/rotate_way.js',
        script + '/id/modes/save.js',
        //script + '/id/modes/select.js',
        script + '/id/modes/add_roadcross.js',
        script + '/id/modes/add_speedcamera.js',
        script + '/id/modes/add_zlevel.js',
        script + '/id/modes/add_walkroad.js',
        script + '/id/modes/add_walk_area.js',
        script + '/id/modes/disconnect_road.js',
        script + '/id/modes/topo_split.js',
        script + '/id/modes/add_island.js',
        script + '/id/modes/add_placename.js',
        script + '/id/modes/add_road_attribute.js',
        script + '/id/modes/add_junction.js',
        appDir + '/modes/select.js',

        appDir + '/modes/road_cross_modify.js',
        //add
        script + '/id/modes/lasso_zoom.js',
        script + '/id/modes/toolbar.js',

        appDir + '/modes/editor_way.js',
        appDir + '/modes/editor_bezier.js',
        appDir + '/modes/lane_info_path_modify.js',
        appDir + '/modes/pic_play.js',
        appDir + '/modes/add_auto_checkwork_tag.js',
        appDir + '/modes/add_pavement_distress_line.js',
        appDir + '/modes/add_pavement_distress_line1.js',
        appDir + '/modes/add_pavement_distress_line2.js',
        appDir + '/modes/add_barrier.js',
        appDir + '/modes/add_object_pt.js',
        appDir + '/modes/draw_barrier.js',
        appDir + '/modes/draw_pavement_distrees.js',
        appDir + '/modes/draw_pavement_distrees1.js',
        appDir + '/modes/add_auto_network_tag.js',
        
        script + '/id/operations.js',
        script + '/id/operations/continue.js',
        script + '/id/operations/circularize.js',
        script + '/id/operations/orthogonalize.js',
        script + '/id/operations/straighten.js',
        script + '/id/operations/bezier_spline.js',
        script + '/id/operations/delete.js',
        script + '/id/operations/disconnect.js',
        script + '/id/operations/merge.js',
        script + '/id/operations/waymerge.js',
        script + '/id/operations/move.js',
        script + '/id/operations/rotate.js',
        script + '/id/operations/reverse.js',
        script + '/id/operations/split.js',
        script + '/id/operations/split_divider.js',
        script + '/id/operations/dividerDREF.js',
        script + '/id/operations/createdividerOPL.js',
        script + '/id/operations/cancle_dividerOPL.js',
        // script + '/id/operations/createdividerOPG.js',
        // script + '/id/operations/cancle_dividerOPG.js',
        script + '/id/operations/createdividerVirtualLane.js',
        script + '/id/operations/createdividerVirtualLaneCircle.js',
        script + '/id/operations/junction.js',
        script + '/id/operations/cancel_relations.js',
        script + '/id/operations/cancel_divider_junction.js',
        script + '/id/operations/road_divider.js',
        script + '/id/operations/update_divider_node.js',
        script + '/id/operations/clone.js',
        script + '/id/operations/copy.js',
        script + '/id/operations/traffic.js',
        script + '/id/operations/lane_traffic.js',
        script + '/id/operations/split_road.js',
        script + '/id/operations/road_intersect.js',
        script + '/id/operations/expand.js',
        script + '/id/operations/expand_dividerNode.js',
        // script + '/id/operations/expand_divider_kerb.js',
        script + '/id/operations/expand_barrier_geometry.js',
        script + '/id/operations/expand_barrier_geometryNode.js',        
        script + '/id/operations/expand_batch_copy.js',        
        script + '/id/operations/topo_split.js',
        script + '/id/operations/roads_move.js',
        script + '/id/operations/clone_tags.js',
		script + '/id/operations/paste_tags.js',
        appDir + '/operations/delete_slope.js',
        appDir + '/operations/diversion_surface_create.js',
        appDir + '/operations/editor_way.js',
        appDir + '/operations/create_bezier_way.js',
        appDir + '/operations/road_cross_create.js',
        appDir + '/operations/road_cross_modify.js',
//      appDir + '/operations/opt_opt_create.js',
//      appDir + '/operations/opt_opt_delete.js',
        appDir + '/operations/auto_generate_way.js',
        appDir + '/operations/autonetworktag_location.js',
        appDir + '/operations/lamppostLREF_create.js',
        appDir + '/operations/measureinfo_copy.js',
        appDir + '/operations/measureinfo_location.js',
        appDir + '/operations/lamppostLREF_delete.js',
        appDir + '/operations/copy_pole_lamp.js',
        appDir + '/operations/paste_pole_lamp.js',
        appDir + '/operations/line_info_modify.js',
        appDir + '/operations/create_separation_points.js',
        appDir + '/operations/create_bridge_point.js',
        // appDir + '/operations/trafficLightTREF.js',
        // appDir + '/operations/trafficLightTREF_delete.js',
        appDir + '/operations/divider_TL_TREF.js',
        appDir + '/operations/divider_TL_TREF_delete.js',
        appDir + '/operations/divider_sideWalk.js',
        appDir + '/operations/divider_stopLine.js',
        appDir + '/operations/road_ra_create.js',
        appDir + '/operations/rectifyDeviationFeature.js',
        appDir + '/operations/copy_board_plane.js',
        appDir + '/operations/boardToEllipse.js',
        appDir + '/operations/paste_board_plane.js',
        appDir + '/operations/rotate_area_divider.js',
        appDir + '/operations/track_point_height_diff.js',
        appDir + '/operations/connect_divider_nodes.js',
        appDir + '/operations/track_control_point.js',
        appDir + '/operations/barrier_divider.js',
        appDir + '/operations/barrier_divider_delete.js',
        appDir + '/operations/barrier_bref.js',
        appDir + '/operations/barrier_bref_delete.js',
        appDir + '/operations/road_facilities.js',
        appDir + '/operations/road_facilities_delete.js',
        appDir + '/operations/divider_tollgate.js',
        appDir + '/operations/divider_tollgate_delete.js',
        appDir + '/operations/divider_tollgate_attribute.js',
        appDir + '/operations/r_divider_opg_create.js',
        appDir + '/operations/r_divider_opg_delete.js',
        appDir + '/operations/r_divider_opl_create.js',
        appDir + '/operations/r_divider_opl_delete.js',
        appDir + '/operations/r_divider_opt_create.js',
        appDir + '/operations/r_divider_opt_delete.js',
        appDir + '/operations/r_lane_tl_create.js',
        appDir + '/operations/r_lane_tl_delete.js',
        appDir + '/operations/r_lane_ts_create1.js',
        appDir + '/operations/r_lane_ts_delete1.js',
        appDir + '/operations/r_lane_ts_create2.js',
        appDir + '/operations/r_lane_ts_delete2.js',
        appDir + '/operations/r_lane_pg_create.js',
        appDir + '/operations/r_lane_pg_delete.js',
        appDir + '/operations/r_road_road_create.js',
        appDir + '/operations/r_road_road_delete.js',
        appDir + '/operations/r_stopline_lane_create.js',
        appDir + '/operations/r_stopline_lane_delete.js',
        appDir + '/operations/r_divider_sign_delete.js',
        appDir + '/operations/r_divider_sign_create.js',
        appDir + '/operations/r_divider_sign_delete.js',
        appDir + '/operations/r_tl_stopline_create.js',
        appDir + '/operations/r_tl_stopline_delete.js',
        // appDir + '/operations/hd_lane_divider.js',
        // appDir + '/operations/hd_lane_divider_delete.js',
        appDir + '/operations/r_road_sign_create.js',
        appDir + '/operations/r_road_sign_delete.js',

        // measureinfo
        appDir + '/measureinfo/measureinfo_handle.js',
        appDir + '/measureinfo/measureinfo_forward_intersection.js',
        appDir + '/measureinfo/measureinfo_normal.js',
        appDir + '/measureinfo/measureinfo_paste.js',
        appDir + '/measureinfo/measureinfo_pan.js',
        appDir + '/measureinfo/measureinfo_split.js',
        appDir + '/measureinfo/measureinfo_vertical_sign.js',
        appDir + '/measureinfo/measureinfo_expand_line.js',
        appDir + '/measureinfo/measureinfo_virtual_line.js',


        // add
        script + '/id/operations/rawposition.js',
        // script + '/id/panorama/qq_api_load.js',
        // script + '/id/panorama/require.js',

        script + '/id/core/layers.js',
        script + '/id/core/connection.js',
        script + '/id/core/difference.js',
        script + '/id/core/entity.js',
        script + '/id/core/graph.js',
        script + '/id/core/history.js',
        script + '/id/core/fileHistory.js',
        script + '/id/core/node.js',
        script + '/id/core/relation.js',
        script + '/id/core/way.js',
        script + '/id/core/tree.js',
        script + '/id/core/area_keys.js',
        script + '/id/core/oneway_tags.js',
        script + '/id/core/model_entity.js',
        script + '/id/core/infowindow.js',

        script + '/id/presets.js',
        script + '/id/presets/preset.js',
        script + '/id/presets/category.js',
        script + '/id/presets/collection.js',
        script + '/id/presets/field.js',


        script + '/id/validate.js',

        script + '/lib/locale.js',
        config + '/introGraph.js',

        '../../api/map-editor-api.src.v1.0.js'
    ];

    //CSS WRITE
    for (var i = 0; i < cssStore.length; i++) {
        var cssUri = "<link rel='stylesheet' type='text/css' href='" + root + cssStore[i] + "'/>";
        document.write(cssUri);
    }

    //SCRIPT WRITE
    //for(var j = 0; j<scriptStore.length; j++){
    //	var doMain = scriptStore[j] === "js/id/panorama/require.js" ? "data-main='"+root+"js/id/panorama/panorama.js'" : '';
    //	var jsUri = "<script type='text/javascript' " + doMain + " src='"+ root + scriptStore[j]+"'></script>";
    //	document.write(jsUri);
    //}
    for (var j = 0; j < scriptStore.length; j++) {
        var jsUri = "<script type='text/javascript' " + scriptStore[j] + " src='" + root + scriptStore[j] + "'></script>";
        document.write(jsUri);
    }
})();